In [24]:
import pandas as pd

In [27]:
csv_file = 'Resources/sub-est2021_1.csv'
census_2021_df = pd.read_csv(csv_file)
census_2021_df.head()

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021
0,40,1,0,0,0,0,0,A,Alabama,Alabama,5024279,5024803,5039877
1,162,1,0,124,0,0,0,A,Abbeville city,Alabama,2368,2368,2379
2,162,1,0,460,0,0,0,A,Adamsville city,Alabama,4372,4356,4294
3,162,1,0,484,0,0,0,A,Addison town,Alabama,664,664,668
4,162,1,0,676,0,0,0,A,Akron town,Alabama,227,227,226

In [29]:
csv_file_2 = 'Resources/SUB-IP-EST2019-ANNRES.csv'
census_2016_df = pd.read_csv(csv_file)
census_2016_df.head()

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021
0,40,1,0,0,0,0,0,A,Alabama,Alabama,5024279,5024803,5039877
1,162,1,0,124,0,0,0,A,Abbeville city,Alabama,2368,2368,2379
2,162,1,0,460,0,0,0,A,Adamsville city,Alabama,4372,4356,4294
3,162,1,0,484,0,0,0,A,Addison town,Alabama,664,664,668
4,162,1,0,676,0,0,0,A,Akron town,Alabama,227,227,226

In [31]:
us_cities_2021 = ['Atlanta',
            'Austin',
            'Baltimore',
            'Boston',
            'Buffalo',
            'Charlotte',
            'Chicago',
            'Cincinnati',
            'Cleveland',
            'Columbus',
            'Dallas',
            'Denver',
            'Detroit',
            'Green Bay',
            'Houston',
            'Indianapolis',
            'Jacksonville',
            'Kansas City',
            'Las Vegas',
            'Los Angeles',
            'Memphis',
            'Miami',
            'Minneapolis',
            'Milwaukee',
            'Nashville',
            'New Orleans',
            'New York',
            'Oakland',
            'Oklahoma City',
            'Orlando',
            'Philadelphia',
            'Phoenix',
            'Pittsburgh',
            'Portland',
            'Raleigh',
            'Sacramento',
            'Salt Lake',
            'San Antonio',
            'San Diego',
            'San Francisco',
            'San Jose',
            'St. Louis',
            'Seattle',
            'Tampa',
            'Washington',]
pro_us_cities_2021 = census_2021_df.loc[census_2021_df['NAME'].isin(us_cities_2021)]
pro_us_cities_2021

Empty DataFrame
Columns: [SUMLEV, STATE, COUNTY, PLACE, COUSUB, CONCIT, PRIMGEO_FLAG, FUNCSTAT, NAME, STNAME, ESTIMATESBASE2020, POPESTIMATE2020, POPESTIMATE2021]
Index: []